// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2KLrCed2T2K-yvD1MP7talTfqqEAt9qo',
    appId: '1:90701682847:web:f9aa5bd35ccceac99ceaaa',
    messagingSenderId: '90701682847',
    projectId: 'vserv-4c063',
    authDomain: 'vserv-4c063.firebaseapp.com',
    storageBucket: 'vserv-4c063.appspot.com',
    measurementId: 'G-8PGQ5258M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkWoHk2xsb0CX0Yj43_WdeygJExlsPawM',
    appId: '1:90701682847:android:5def72648a06bf309ceaaa',
    messagingSenderId: '90701682847',
    projectId: 'vserv-4c063',
    storageBucket: 'vserv-4c063.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKyesWYvJYv_tRB59Dp875CotjpLNvpAc',
    appId: '1:90701682847:ios:e5379e8c3979096b9ceaaa',
    messagingSenderId: '90701682847',
    projectId: 'vserv-4c063',
    storageBucket: 'vserv-4c063.appspot.com',
    iosClientId: '90701682847-tee12jtfq4ich0vc7m9bij91ljplsqee.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKyesWYvJYv_tRB59Dp875CotjpLNvpAc',
    appId: '1:90701682847:ios:e5379e8c3979096b9ceaaa',
    messagingSenderId: '90701682847',
    projectId: 'vserv-4c063',
    storageBucket: 'vserv-4c063.appspot.com',
    iosClientId: '90701682847-tee12jtfq4ich0vc7m9bij91ljplsqee.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );
}
